### ISSUE TITLE
Tests: "dictionary changed size during iteration"

### ISSUE THREAD

**Issue by cmarxer** [cn-uofbasel/PiCN#4]
It occurs very rarely that a test fails with to the following output.
Looks like a race condition?

```
> python3 setup.py nosetests
running nosetests
running egg_info
writing PiCN.egg-info/PKG-INFO
writing dependency_links to PiCN.egg-info/dependency_links.txt
writing top-level names to PiCN.egg-info/top_level.txt
reading manifest file 'PiCN.egg-info/SOURCES.txt'
writing manifest file 'PiCN.egg-info/SOURCES.txt'
Searching for nose2
Best match: nose2 0.7.3
Processing nose2-0.7.3-py3.6.egg

Using /home/claudio/software/PiCN/.eggs/nose2-0.7.3-py3.6.egg
Searching for coverage>=4.4.1
Best match: coverage 4.4.2
Processing coverage-4.4.2-py3.6-linux-x86_64.egg

Using /home/claudio/software/PiCN/.eggs/coverage-4.4.2-py3.6-linux-x86_64.egg
.............................................................................
.............................................................................
...........................Exception in thread Thread-88:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/claudio/software/PiCN/PiCN/Layers/NFNLayer/BasicNFNLayer.py", line 172, in handle_computation_queue
    for cid in running_computations.keys():
RuntimeError: dictionary changed size during iteration
```

**Comment by blacksheeep** [comment]
I think the interference comes from the aging thread. thus this part should acquire a lock.

**Comment by cmarxer** [comment]
It seems to me that this solves the problem. At least, the problem didn't occur during many test runs.
